### ISSUE TITLE
A solution about the incompatibilities of the Sophisticated Wolves.

### ISSUE THREAD

**Issue by gsbaoge** [CenturionFox/wolfarmor#4]
At first, I wana thanks for you brilliant works about this mod!
But it is a pity that about this mod has the incompatibilities problem with Sophisticated Wolves.

I think the key is you should using the [forge capability system](https://mcforge.readthedocs.io/en/latest/datastorage/capabilities/) to instead the old method. which is create a wolf entity. because another wolf mod may create the wolf entity their own. 

I aready have a code [here](https://github.com/gsbaoge/wolfarmor/tree/1.10.2). but it maybe very buggy. so I doesn't send a pullrequest for it. Hopely that will give you some help. And sorry for my bad English.

**Comment by CenturionFox** [comment]
That would probably also help with Issue #1, which was caused with an incompatibility with the capability system used in that mod.

If I create a new branch off of 1.10, can you do a pull request into that?

**Comment by CenturionFox** [comment]
I read the graph wrong. I can create a 1.11-testing branch instead.

**Comment by gsbaoge** [comment]
I didn't read it wrong. I am aready send the pull request to the "1.10.2-testing" branch . Because I test it in 1.10.2.

**Comment by CenturionFox** [comment]
I built the testing branch to an alpha version and put that over on the curse page for anybody who wants to test it out.  Thanks for your assistance, it's very much appreciated!

**Comment by NightKosh** [comment]
Hello. Could you please explain how you store items and armor?
I added a new item - "pet carrier" to Sophisticated wolves mod(in 1.11.2), which can be used to transport wolves(and another pets). It takes all wolves data from its NBT ( wolf.writeToNBT(...) ) and restore all information about it in the same way (wolf.readEntityFromNBT(...) ). So I'm wondering will it be compatible with your mod or not?

P.S. Thank you very much for compatibility fix.

**Comment by CenturionFox** [comment]
Hey NightKosh,

After gsbaoge's fix, the wolf armor data is stored in the NBT under the capabilities list of the wolf.  Essentially the inventory of the wolf is stored in the same way that a chest stores its data, just within the capability object instead of on the entity itself.  Storing and restoring capabilities is handled in the base Entity class (I think; it's either that or EntityLiving), so since your pet carrier is using the base read and write methods, it should work fine, at least after this patch is finally merged to 1.11.2.

As of late I've been unable to work much on this project due to time constraints, but I think I should have the patch out by early July at the latest. That said, the 1.11-testing branch should be merged into earlier, and I'll probably release an alpha version.  I'll let you know when I've done that if you'd like to test for any incompatibilities yourself, though I will definitely run my own tests with the latest version of your mod.

As it stands, the 1.11 version I currently have released will not work, but once I merge this patch from 1.10 I don't think you'll need to make any compatibility changes yourself.

Thanks!
